on:
  push:
    branches: [ "main" ]
      
name: Build Go App

env:
  DIRECTORY: "test-directory"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Check config
      run: "echo $env.DIRECTORY"

