on:
  workflow_dispatch:
    inputs:
      service-name:
        type: choice
        description: Which dev to push to
        required: true
        default: 'neonmoose'
        options:
        - neonmoose
        - neonmoose-mike
        - neonmoose-jahan
        - neonmoose-armin
        - neonmoose-harrison
        - neonmoose-tyler
        - neonmoose-ken
        - neonmoose-james
        - neonmoose-tariq
        - neonmoose-dane
      
name: Build Go App

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.service-name}}
    steps:
    - uses: actions/checkout@v3

    - name: Set Directory
      run: | 
        echo "DIRECTORY=${{github.event.inputs.service-name}}" >> $GITHUB_ENV

    - name: Check config
      run: "echo ${{ env.DIRECTORY }}"


