on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Build Go App

env:
  DIRECTORY: test



jobs:
  build:
    runs-on: ubuntu-latest
    env:
      directory: ${{ env.DIRECTORY }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./main.go
